# AWS CodeBuild buildspec for Nitro Enclave EIF generation
# This runs on an EC2 instance with Nitro Enclave support

version: 0.2

env:
  variables:
    # These are overridden by the GitHub Actions workflow
    APP_NAME: "example-app"
    APP_VERSION: "1.0.0"
    IMAGE_URI: ""
    DEBUG_MODE: "false"
    S3_BUCKET: "nova-app-hub-artifacts"
    SOURCE_COMMIT: ""
    SOURCE_COMMIT_SHORT: ""
    GITHUB_RUN_ID: ""

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing AWS Nitro CLI..."
      - amazon-linux-extras install aws-nitro-enclaves-cli -y
      - yum install aws-nitro-enclaves-cli-devel -y
      - systemctl enable nitro-enclaves-allocator.service
      - systemctl start nitro-enclaves-allocator.service
      - nitro-cli --version
      - echo "Nitro CLI installed successfully"

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $IMAGE_URI | cut -d'/' -f1)
      
      - echo "Pulling Docker image..."
      - docker pull $IMAGE_URI
      
      - echo "Verifying image..."
      - docker inspect $IMAGE_URI
      
      - echo "Pre-build completed successfully"

  build:
    commands:
      - echo "Building Nitro Enclave EIF..."
      - echo "  App Name: $APP_NAME"
      - echo "  Version: $APP_VERSION"
      - echo "  Image URI: $IMAGE_URI"
      - echo "  Debug Mode: $DEBUG_MODE"
      
      - mkdir -p output
      
      # Build EIF with or without debug mode
      - |
        if [ "$DEBUG_MODE" = "true" ]; then
          echo "Building EIF in DEBUG mode (PCR values will differ)..."
          nitro-cli build-enclave \
            --docker-uri $IMAGE_URI \
            --output-file output/${APP_NAME}.eif \
            --debug-mode 2>&1 | tee output/build-output.txt
        else
          echo "Building EIF in PRODUCTION mode..."
          nitro-cli build-enclave \
            --docker-uri $IMAGE_URI \
            --output-file output/${APP_NAME}.eif 2>&1 | tee output/build-output.txt
        fi
      
      - echo "EIF build completed"
      
      # Extract PCR values from build output
      - |
        echo "Extracting PCR values..."
        PCR0=$(grep -oP '"PCR0":\s*"\K[^"]+' output/build-output.txt || echo "")
        PCR1=$(grep -oP '"PCR1":\s*"\K[^"]+' output/build-output.txt || echo "")
        PCR2=$(grep -oP '"PCR2":\s*"\K[^"]+' output/build-output.txt || echo "")
        
        echo "PCR0: $PCR0"
        echo "PCR1: $PCR1"
        echo "PCR2: $PCR2"
        
        # Create PCR JSON file
        cat > output/pcr.json << EOF
        {
          "PCR0": "$PCR0",
          "PCR1": "$PCR1",
          "PCR2": "$PCR2"
        }
        EOF
        
        echo "PCR values saved to pcr.json"
      
      # Create build info JSON
      - |
        cat > output/build-info.json << EOF
        {
          "app_name": "$APP_NAME",
          "version": "$APP_VERSION",
          "image_uri": "$IMAGE_URI",
          "source_commit": "$SOURCE_COMMIT",
          "source_commit_short": "$SOURCE_COMMIT_SHORT",
          "debug_mode": $DEBUG_MODE,
          "github_run_id": "$GITHUB_RUN_ID",
          "build_timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')",
          "pcr": {
            "PCR0": "$PCR0",
            "PCR1": "$PCR1",
            "PCR2": "$PCR2"
          }
        }
        EOF
      
      - echo "Build info saved to build-info.json"
      - cat output/build-info.json

  post_build:
    commands:
      - echo "Uploading artifacts to S3..."
      - aws s3 cp output/${APP_NAME}.eif s3://${S3_BUCKET}/builds/${APP_NAME}/${APP_VERSION}/${APP_NAME}.eif
      - aws s3 cp output/pcr.json s3://${S3_BUCKET}/builds/${APP_NAME}/${APP_VERSION}/pcr.json
      - aws s3 cp output/build-info.json s3://${S3_BUCKET}/builds/${APP_NAME}/${APP_VERSION}/build-info.json
      - aws s3 cp output/build-output.txt s3://${S3_BUCKET}/builds/${APP_NAME}/${APP_VERSION}/build-output.txt
      
      - echo "Artifacts uploaded successfully"
      - echo "  EIF: s3://${S3_BUCKET}/builds/${APP_NAME}/${APP_VERSION}/${APP_NAME}.eif"
      - echo "  PCR: s3://${S3_BUCKET}/builds/${APP_NAME}/${APP_VERSION}/pcr.json"
      
      # Verify uploads
      - aws s3 ls s3://${S3_BUCKET}/builds/${APP_NAME}/${APP_VERSION}/
      
      - echo "Build completed successfully!"

artifacts:
  files:
    - output/${APP_NAME}.eif
    - output/pcr.json
    - output/build-info.json
    - output/build-output.txt
  discard-paths: no

cache:
  paths:
    - '/var/lib/docker/**/*'
